name: Run Azure Login with OpenID Connect
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
      id-token: write
      contents: read
directCommands:
- uid: az_webapp_browse
  name: az webapp browse
  summary: Open a web app in a browser.
  description: ''
  syntax: >-
    az webapp browse [--ids]
                     [--logs]
                     [--name]
                     [--resource-group]
                     [--slot]
                     [--subscription]
      
jobs: 
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 'Az CLI login'
      uses: azure/login@v1
      with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  
    - name: 'Run Azure CLI commands'
      run: |
          az account show
          az group list
          pwd
